- name: Prepare hosts for OpenShift installation
  become: False
  hosts: nodes

  tasks:
    - name: Workaround for k8s#13511
      ini_file: dest=/usr/lib/systemd/system/atomic-openshift-node.service
                section=Service
                option=KillMode
                value=process
      notify:
        - reload systemd

    - name: Configure OpenShift Gluster plugin logrotate
      copy: src=files/glusterfs-plugin dest=/etc/logrotate.d owner=root group=root mode=0644 setype=etc_t

    - name: Configure MAILTO of docker-cleanup cron job
      lineinfile:
        state: "{{ (appuio_docker_cleanup_mail is defined) | ternary('present', 'absent') }}"
        dest: /etc/cron.hourly/docker-cleanup
        line: 'MAILTO="{{ appuio_docker_cleanup_mail | default("") }}"'
        regexp: MAILTO=
        insertafter: ^#!

    - local_action: yum name={{ openshift_package_name }} state=latest
      run_once: true

  handlers:
    - name: restart Docker
      service: name=docker state=restarted

    - name: restart OpenShift node
      service: name={{ openshift_package_name }}-node state=restarted

    - name: reload systemd
      command: systemctl daemon-reload
