# These tasks work around https://github.com/ansible/ansible/issues/19305 and
# https://github.com/ansible/ansible/issues/19084.
# When these issues are fixed include_role can be used directly in the playbook

- set_fact:
    role_name: "{{ role_name }}"
  args: "{{ role_vars }}"

- name: "Run post-install role '{{ role_name }}'"
  include_role:
    name: "{% for key in hostvars.keys() %}{{ hostvars[key | string].get('role_name') }}{% endfor %}"
